services:
  - type: web
    name: flask-todo-cicd
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000

