services:
  - type: web
    name: flask-todo-cicd
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 run:app

    envVars:
      - key: FLASK_ENV
        value: production

      - key: PYTHON_VERSION
        value: 3.11.9

      - key: PORT
        value: 5001

      - key: DATABASE_URL
        value: postgresql://postgres:postgres@db:5432/todo_dev
